name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer, cs2pr
      - name: Build Artifact
        run: |
          git submodule update --init --recursive
          composer install
          composer translations
          rm -rf /vendor
          composer install --no-dev
          cd ${{ github.workspace }}/onlyoffice-wordpress-block
          npm install
          npm run build
          rm -rf node_modules
          rm package.json
          rm package-lock.json
          rm .eslintrc
          cd ${{ github.workspace }}
          mkdir -p ./deploy/onlyoffice
          rsync -av --exclude='deploy' ./ ./deploy/onlyoffice
          cd ./deploy/onlyoffice
          rm -rf ./.github/
          rm -rf ./.git/
          rm ./.gitignore
          rm composer.json
          rm composer.lock
          rm .csscomb.json
          rm .gitmodules
          rm public/assets/document-formats/.git
          rm public/assets/document-formats/README.md
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: onlyoffice
          path: deploy
