name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          mkdir -p ./deploy/onlyoffice
          rsync -av --exclude='deploy' ./ ./deploy/onlyoffice
          cd ./deploy/onlyoffice
          rm -rf ./.github/
          rm -rf ./.git/
          rm ./.gitignore
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: onlyoffice
          path: deploy
