name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Info
        run: |
          echo "::set-output name=version::$(grep -Eo '[0-9]+(\.[0-9]+)+' CHANGELOG.md)"
        id: info
      - name: Generate Changelog
        run: |
          awk '/## [0-9]/{p++} p; /## [0-9]/{if (p > 1) exit}' CHANGELOG.md | awk 'NR>2 {print last} {last=$0}' > RELEASE.md
      - name: Install Zip
        run: sudo apt-get install zip
      - name: Build Plugin
        run: |
          cd ${{ github.workspace }}
          mkdir -p ./onlyoffice
          rsync -av --exclude='onlyoffice' ./ ./onlyoffice
          cd ./onlyoffice
          rm -rf .github/
          rm -rf .git/
          rm .gitignore
      - name: Build Artifact
        run: zip -r onlyoffice.zip onlyoffice/
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.info.outputs.version }}
          tag_name: v${{ steps.info.outputs.version }}
          body_path: ./RELEASE.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: onlyoffice.zip
          asset_name: onlyoffice.zip
          asset_content_type: application/zip
